NUM_GPUS: 1
NUM_SHARDS: 1
SHARD_ID: 0
RNG_SEED: 0
LOG_FILE_PATH: ./logs/
INIT_METHOD: tcp://localhost:9999
AMP_ENABLE: False
TRAIN:
  ENABLE: True
  MAX_EPOCH: 10
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 5
  CHECKPOINT_EPOCH_RESET: FALSE
  CHECKPOINT_LOAD_PATH: ''
  CHECKPOINT_SAVE_PATH: '.'
TEST:
  ENABLE: True
  TEST_CHECKPOINT_PATH: ''
MODEL:
  FIND_UNUSED_PARAMETERS: False
DATASET:
  DATASET_NAME: CelebDF
  ROOT_DIR: data/Celeb-DF
  TRAIN_INFO_TXT: data/Celeb-DF-Face/splits/train_list.txt
  VAL_INFO_TXT: data/Celeb-DF-Face/splits/val_list.txt
  TEST_INFO_TXT: data/Celeb-DF-Face/splits/test_list.txt
  IMG_SIZE: 380
  TRAIN_AUGMENTATIONS:
    COMPOSE:
      [
        Resize,
        Normalize
      ]
    NORMALIZE_PARAMS: [[0.485, 0.456, 0.406], [0.229, 0.224, 0.225]]
  TEST_AUGMENTATIONS:
    COMPOSE: [Resize, Normalize]
    NORMALIZE_PARAMS: [[0.485, 0.456, 0.406], [0.229, 0.224, 0.225]]
DATALOADER:
  BATCH_SIZE: 16
  NUM_WORKERS: 4
  PIN_MEM: True
LOSS:
  LOSS_FUN: FocalLoss
OPTIMIZER:
  OPTIMIZER_METHOD: adamw
  BASE_LR: 0.001
  ADAM_BETAS: [0.9, 0.999]
  EPS: 0.00000001
  WEIGHT_DECAY: 0.01
  AMSGRAD: False
SCHEDULER:
  LR_NOISE_PCT: 0.67
  LR_NOISE_STD: 1.0
  SEED: 42
  LR_CYCLE_MUL: 1.0
  LR_CYCLE_DECAY: 0.1
  LR_CYCLE_LIMIT: 1
  SCHEDULER_TYPE: cosine
  MIN_LR: 0.000001
  WARMUP_LR: 0
  WARMUP_EPOCHS: 0
  COOLDOWN_EPOCHS: 10
  LR_K_DECAY: 1.0
  SCHEDULER_STEP: 5
  SCHEDULER_GAMMA: 0.5
